<a href="https://colab.research.google.com/github/hugoalfedoputra-ub/ml/blob/main/nn_practice/JST_CH2_Hugo_Alfedo_Putra_225150201111013.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hebb net

In [54]:
import numpy as np

# Definisikan data untuk huruf L, U, I, dan O berdasarkan studi kasus
data_L = 1, -1, -1, 1, -1, -1, 1, 1, 1
data_U = 1, -1, 1, 1, -1, 1, 1, 1, 1
data_I = 1, 1, 1, -1, 1, -1, 1, 1, 1
data_O = 1, 1, 1, 1, -1, 1, 1, 1, 1

# ones untuk definisi bias
ones = np.ones((2,1))

# target adalah target, L itu 1 dan U itu -1
target = 1, -1

# Definisikan semua weight dan bobot menjadi 0
w = [0 for _ in range(len(data_L))]
b = [0]

In [67]:
def bipstep(net, th=0):
  return 1 if net>=th else -1

temp = np.vstack((data_L, data_U))
data = np.hstack((temp, ones))
wb = np.hstack((w, b))
th = 0

wb_baru = [0 for _ in range(len(wb))]
for r, row in enumerate(data):
  print('Baris ke', r)
  print(row)
  wb_baru = np.add(wb_baru, [wb[i] + row[i] * target[r] for i in range(len(row))])
  print('Memiliki bobot-bobot')
  print(wb_baru)
  print()

w_out = wb_baru[:-1]
b_out = wb_baru[-1]
print(f'Bobot-bobot akhir:\n{w_out}\n')
print(f'Bias akhir:\n{b_out}\n')

net_I = np.dot(data_I, w_out) + b_out
net_O = np.dot(data_O, w_out) + b_out
print('Huruf I termasuk golongan:', 'L' if bipstep(net_I, th)>=th else 'U')
print('Huruf O termasuk golongan:', 'L' if bipstep(net_O, th)>=th else 'U')

Baris ke 0
[ 1. -1. -1.  1. -1. -1.  1.  1.  1.  1.]
Memiliki bobot-bobot
[ 1. -1. -1.  1. -1. -1.  1.  1.  1.  1.]

Baris ke 1
[ 1. -1.  1.  1. -1.  1.  1.  1.  1.  1.]
Memiliki bobot-bobot
[ 0.  0. -2.  0.  0. -2.  0.  0.  0.  0.]

Bobot-bobot akhir:
[ 0.  0. -2.  0.  0. -2.  0.  0.  0.]

Bias akhir:
0.0

Huruf I termasuk golongan: L
Huruf O termasuk golongan: U


# Hasil akhir

```
Baris ke 0
[ 1. -1. -1.  1. -1. -1.  1.  1.  1.  1.]
Memiliki bobot-bobot
[ 1. -1. -1.  1. -1. -1.  1.  1.  1.  1.]

Baris ke 1
[ 1. -1.  1.  1. -1.  1.  1.  1.  1.  1.]
Memiliki bobot-bobot
[ 0.  0. -2.  0.  0. -2.  0.  0.  0.  0.]

Bobot-bobot akhir:
[ 0.  0. -2.  0.  0. -2.  0.  0.  0.]

Bias akhir:
0.0

Huruf I termasuk golongan: L
Huruf O termasuk golongan: U
```